### ISSUE TITLE
Make PAL mirror FR/catFR

### ISSUE THREAD

**Issue by zduey** [pennmem/event_creation#6]
There are a few differences between PAL and FR/catFR events that require some additional normalization if events are to be combined across those experiments. Specifically, a recall event is stored in the 'recalled' field for FR/catFR, but stored in the 'correct' field in PAL. These should be stored in the same field, perhaps 'recalled' so that only PAL events would need to be changed.

**Comment by jrudoler** [comment]
No longer really relevant
