### ISSUE TITLE
Remove "test" field from events structures

### ISSUE THREAD

**Issue by zduey** [pennmem/event_creation#9]
I'm not sure if it occurs for all experiment types, but there is a field called "test" that holds an array of three zeros for no apparent reason. For example, it can be found in the all_events.json file for R1374T, catFR5 session 0. If this field does not get used, whatever part of the code is creating should be removed.

**Comment by leondavis1** [comment]
This isn't actually a bug -- the 'test' field is from the math events, and describes the problem posed.
'Test' is just a slightly unfortunate name for it

**Comment by zduey** [comment]
Ok, gotcha. Thanks.
